import Link from 'next/link'

const metricCards = [
  ['electricity', 'Electricity and grid', '⚡', 'Load, capacity, grid connection, and regional system effects.'],
  ['water', 'Water consumption', '💧', 'Cooling method, WUE, direct water use, and watershed context.'],
  ['air', 'Air pollution and generation', '≋', 'Backup generation, fuel, permits, emissions, and dispersion context.'],
  ['sound', 'Sound pollution', '〰', 'Cooling, generators, transformers, barriers, and off-site sound.'],
  ['vibration', 'Vibration', '⌁', 'Generators, transformers, construction, and site-specific measurements.'],
  ['construction', 'Construction and traffic', '🚧', 'Construction phase, truck routes, traffic counts, and operating activity.'],
  ['land', 'Land and flood context', '⌂', 'Footprint, drainage, floodplain, wildlife, zoning, and surrounding land use.'],
]

export default function CalculatorPage() {
  return <main className="learn-page calculator-page">
    <header className="topbar"><Link href="/" className="brand"><span className="brand-mark">D</span><span>DATA CENTER <i>IMPACT</i></span></Link><Link href="/" className="back">← Back to map</Link></header>
    <article className="article"><p className="eyebrow">WORK IN PROGRESS · CALCULATOR</p><h1>We are not ready to calculate this yet.</h1><p className="article-dek">The calculator is being designed in public. These are working theories and personal opinions about how a transparent screening tool might work, not scientific conclusions or finished product behavior.</p><div className="article-meta">Draft direction · Open for suggestions</div>
      <div className="article-layout"><div className="article-body">
        <div className="article-callout calculator-disclaimer"><strong>Personal opinion, not a published model.</strong><p>This page describes one possible approach from the project team. It should not be used to make health, legal, environmental, appraisal, or purchase decisions. Suggestions and criticism are welcome through the project’s <a href="https://github.com/christophermowrey/datacenterimpact/issues/new?template=correction.yml" target="_blank" rel="noreferrer">GitHub issue tracker ↗</a>.</p></div>
        <h2 id="two-calculators">Two calculators, eventually</h2><div className="calculator-cards"><section><span className="calculator-number">01</span><h3>Immediate impact</h3><p>A single-facility view: what potential effects might be most relevant at a chosen distance from one data center?</p><strong>Likely inputs</strong><p>Facility scale, electricity demand, cooling and water evidence, backup generation, noise, vibration, land context, and distance.</p><span className="coming-soon-label">Coming soon · no live score yet</span></section><section><span className="calculator-number">02</span><h3>Address impact</h3><p>A cumulative view: what might happen when multiple facilities and regional infrastructure affect the same address?</p><strong>Likely inputs</strong><p>Every included facility, distance and direction where relevant, shared utility or watershed context, and uncertainty in each source record.</p><span className="coming-soon-label">Coming soon · no live score yet</span></section></div>
        <h2 id="metrics">Metrics we measure</h2><p>These are the same community-facing categories shown on facility detail pages. They are evidence cards, not live calculator outputs. Each future calculator would need to decide how much of each category is supported, estimated, proxied, or unknown.</p><div className="calculator-metrics-grid">{metricCards.map(([key, label, icon, description]) => <article className="calculator-metric-card" key={key}><span className="calculator-metric-icon" aria-hidden="true">{icon}</span><h3>{label}</h3><p>{description}</p><span className="coming-soon-label">Evidence category</span></article>)}</div>
        <h2 id="working-theories">Working theories</h2><div className="theory-grid"><div><h3>Use ranges, not false precision</h3><p>Each category would have a lower and upper bound. The lower bound would use documented facts; the upper bound would include clearly labeled conservative proxies when important facts are missing. The overall screening scale would likely be bounded from <strong>0 to 100</strong>, but the thresholds and labels are not decided.</p></div><div><h3>Distance should be category-specific</h3><p>Sound and vibration may use steep distance decay informed by engineering propagation, while electricity and water may retain a regional floor because grids and watersheds do not stop at a parcel boundary. Air effects should use dispersion concepts, not a generic inverse-square shortcut.</p></div><div><h3>Multiple facilities should accumulate</h3><p>Two facilities 20 miles away should not look identical to one facility 20 miles away. A future address model could combine bounded contributions with a diminishing-returns rule, then separately show shared regional effects so cumulative impact is visible without pretending the inputs are independent measurements.</p></div><div><h3>Thresholds need evidence</h3><p>Minimum and maximum thresholds should come from defensible benchmarks where possible, not arbitrary UI settings. A missing value should widen uncertainty, not silently become zero impact. We still need to decide how thresholds vary by facility type, operating status, and measured versus reported data.</p></div></div>
        <h2 id="backlog">Backlog additions</h2><p>Heat production and illumination should be considered as separate categories. Waste heat may matter for local microclimate or equipment exhaust context, while illumination or light pollution may affect sleep, dark-sky conditions, and nearby residents. Neither is currently scored.</p><ul><li>Research usable heat-output and cooling-exhaust proxies.</li><li>Research nighttime lighting, glare, shielding, and facility design evidence.</li><li>Decide whether these belong in immediate impact, address impact, or both.</li><li>Find public measurement and permitting sources before assigning ranges.</li></ul>
        <div className="article-callout"><strong>Have a better theory?</strong><p>Open a GitHub issue with the assumption, evidence, and a concrete example. The goal is a model people can inspect and challenge, not a mysterious number that looks authoritative.</p></div>
      </div><aside className="article-aside"><p className="eyebrow">ON THIS PAGE</p><a href="#two-calculators">Two calculators</a><a href="#metrics">Metrics we measure</a><a href="#working-theories">Working theories</a><a href="#backlog">Backlog additions</a><div className="aside-note">This page is intentionally unfinished. The absence of a live calculator is a product decision, not a missing result.</div></aside></div>
    </article>
  </main>
}
