import Link from 'next/link'

const sources = [
  ['Data Center Map Houston directory', 'https://www.datacentermap.com/usa/texas/houston/'],
  ['Baxtel Houston market', 'https://baxtel.com/data-center/houston'],
  ['ERCOT overview', 'https://www.ercot.com/about'],
  ['Texas Comptroller data centers', 'https://comptroller.texas.gov/economy/local/ch313/data-centers.php'],
]

export default function LearnPage() {
  return <main className="learn-page">
    <header className="topbar"><Link href="/" className="brand"><span className="brand-mark">D</span><span>DATA CENTER <i>IMPACT</i></span></Link><Link href="/" className="back">← Back to map</Link></header>
    <article className="article"><p className="eyebrow">AI DATA CENTERS · HOUSTON AREA</p><h1>Understand what is near your home.</h1><p className="article-dek">Data Center Impact is an address-first way to investigate AI and other data-center infrastructure without treating directory listings, announcements, or assumptions as the same thing.</p><div className="article-meta">Updated July 2026 · Houston-area coverage expanding</div>
      <div className="article-layout"><div className="article-body">
        <p>An AI data center is still a data center: a building or campus for servers, networking, storage, cooling, power, fiber, and backup systems. The map uses the broader data-center category because operators do not always disclose workloads, and a facility can support cloud, enterprise, colocation, AI, or other compute over time.</p>
        <h2 id="check">Start with an address</h2><p>Enter a home address, neighborhood, or ZIP code to see the searched location, nearby facilities, lifecycle status, distance, evidence confidence, and screening impact range. The map currently covers the Houston area and is expanding to The Woodlands, Brazoria, Galveston, College Station, Conroe, Victoria, and nearby regional locations.</p>
        <h2 id="statuses">Three lifecycle groups</h2><div className="article-cards"><div><strong>Built</strong><p>Operational or substantially completed facilities. Smaller carrier and network facilities are included when they represent a physical data-center or colocation site.</p></div><div><strong>Under construction</strong><p>Construction evidence exists. A new building or campus phase may be related to an existing facility.</p></div><div><strong>Announced</strong><p>Planned, prospective, shadow-announced, or uncertain projects. These remain visible with clear confidence labels instead of being silently discarded.</p></div><div><strong>Additional network facilities</strong><p>Carrier hotels, network hubs, and smaller colocation rooms can be toggled as a separate class while remaining in the inventory.</p></div></div>
        <h2 id="sources">What counts as evidence?</h2><p>Data Center Map and Baxtel are useful business directories for discovering names, addresses, operators, campuses, and phases. They are not treated as a single final authority. Our normalized inventory preserves their listings and compares them with operator pages, permits, utility records, government sources, and reputable reporting.</p><p>Sources can disappear or change. We retain the published facts, access date, source role, original URL, and available snapshot metadata so a removed listing does not erase the historical basis for a record.</p>
        <h2 id="power">Electricity scale</h2><p>Where a source lists power in kW or MW, the profile also shows an approximate Texas-home equivalent. The screening comparison uses 1.5 kW of average continuous household draw. It is a capacity comparison, not disclosed actual consumption.</p><p>Anything above 100 homes equivalent is considered significant for this project and starts at one electricity point before local distance effects are considered. A 26 MW listed capacity is approximately 17,333 homes equivalent. Actual electricity use may be lower or vary over time.</p>
         <h2 id="impact">What the impact range means</h2><p>The score is a transparent screening range, not a medical conclusion, property-value forecast, legal opinion, or environmental impact assessment. Water and electricity retain regional effects; air uses an atmospheric-dispersion screening proxy; sound and vibration attenuate faster with distance. The formulas and scientific references are documented in the <a href="/about#science">methodology notes</a>.</p>
         <h2 id="science">Distance and science</h2><p>We do not use a single inverse-square rule for every category. The <a href="https://www.epa.gov/scram/air-quality-dispersion-modeling" target="_blank" rel="noreferrer">EPA air-dispersion framework</a> uses emissions, meteorology, and downwind receptors. Outdoor sound is evaluated using engineering propagation methods such as <a href="https://www.iso.org/standard/20649.html" target="_blank" rel="noreferrer">ISO 9613-2</a>. Water and grid effects are modeled with regional floors because watersheds, utility capacity, and interconnected systems do not end at a five-mile circle.</p>
        <h2 id="questions">Questions to ask</h2><ol><li>Is the record built, under construction, or announced?</li><li>Is the location exact, approximate, or only a candidate point?</li><li>Which facts come from an operator, permit, utility, government record, directory, or reporting?</li><li>Is the listing a campus, building, phase, carrier room, or duplicate provider record?</li><li>What power, cooling, water, generation, noise, traffic, and land-use facts remain unknown?</li></ol>
        <div className="article-callout"><strong>Start with evidence.</strong><p>Use the map for orientation, open the facility profile and source links, and perform independent legal, environmental, appraisal, and inspection due diligence.</p></div>
        <h2>Further reading</h2><ul className="article-sources">{sources.map(([label, url]) => <li key={url}><a href={url} target="_blank" rel="noreferrer">{label} ↗</a></li>)}</ul>
      </div><aside className="article-aside"><p className="eyebrow">IN THIS GUIDE</p><a href="#check">Start with an address</a><a href="#statuses">Lifecycle groups</a><a href="#sources">Evidence and sources</a><a href="#power">Electricity scale</a><a href="#impact">Impact range</a><a href="#questions">Questions to ask</a><div className="aside-note">AI is the acquisition language. Data center is the inventory category.</div></aside></div>
    </article>
  </main>
}
