import Link from 'next/link'

export default function AboutPage() {
  return <main className="learn-page">
    <header className="topbar"><Link href="/" className="brand"><span className="brand-mark">D</span><span>DATA CENTER <i>IMPACT</i></span></Link><Link href="/" className="back">← Back to map</Link></header>
    <article className="article"><p className="eyebrow">ABOUT THE DATA</p><h1>How Data Center Impact works.</h1><p className="article-dek">A practical guide to the Houston-area inventory, sources, lifecycle labels, impact ranges, and limits of the screening model.</p><div className="article-meta">Updated July 2026 · Houston-area coverage expanding</div>
      <div className="article-layout"><div className="article-body">
        <h2 id="coverage">Coverage</h2><p>Current coverage includes Houston and nearby regional locations, with expansion to The Woodlands, Brazoria, Galveston, College Station, Conroe, Victoria, and surrounding communities. The map is expanding and is not yet a complete inventory.</p>
        <h2 id="statuses">Lifecycle labels</h2><div className="article-cards"><div><strong>Built</strong><p>Operational or substantially completed facilities.</p></div><div><strong>Under construction</strong><p>Construction evidence exists for a facility or phase.</p></div><div><strong>Announced</strong><p>Planned, prospective, shadow-announced, or uncertain projects kept visible for research.</p></div><div><strong>Network facilities</strong><p>Smaller carrier rooms, network hubs, and colocation sites remain included and are shown by default in staging.</p></div></div>
        <h2 id="sources">Sources</h2><p>Our normalized inventory is the source of truth. Data Center Map, Baxtel, operator pages, government records, permits, utilities, and reputable reporting are attached as source records. Directory listings are valuable discovery sources, but their counts and facility boundaries differ.</p><p>When a source changes or disappears, we preserve the source URL, access date, captured facts, source role, and available snapshot metadata. A changed source does not silently erase the historical record.</p>
        <h2 id="impact">Impact ranges</h2><p>Each result displays an estimated Neighborhood Impact range from <strong>0 to 100</strong>. The range is a screening tool, not a medical conclusion, property-value forecast, legal opinion, or environmental impact assessment.</p><p>Interpretation bands are Minimal (0–19), Low (20–39), Moderate (40–59), High (60–79), and Very high (80–100). A range crossing bands is described using both labels.</p>
        <h2 id="preliminary">Preliminary candidates</h2><p>Staging may show research candidates with approximate locations and directory-based evidence. These records can contribute to preliminary Community Impact ranges so the staging map reflects the broader research inventory, but the location, lifecycle, operator, and technical facts may still change. Candidate records are not presented as equally verified facilities and remain disabled in the production publication layer until reviewed.</p>
        <h2 id="electricity">Electricity scale</h2><p>When a source lists power in kW or MW, the detailed facility page shows an approximate Texas-home equivalent using 1.5 kW of average continuous household draw. This compares listed capacity, not disclosed actual consumption.</p><p>Facilities above 100 homes equivalent are considered significant and start at one electricity-impact point before local distance effects are considered.</p>
        <h2 id="limits">Important limits</h2><p>Unknown data widens a result range and lowers detailed-page evidence confidence. Location precision may be exact, approximate, or candidate. The inventory includes uncertain announced projects intentionally, but users should verify material facts independently before making legal, environmental, appraisal, or inspection decisions.</p>
        <div className="article-callout"><strong>Found something missing or wrong?</strong><p>Use the correction action on a facility page and include the source or public record that should be reviewed.</p></div>
      </div><aside className="article-aside"><p className="eyebrow">ON THIS PAGE</p><a href="#coverage">Coverage</a><a href="#statuses">Lifecycle labels</a><a href="#sources">Sources</a><a href="#impact">Impact ranges</a><a href="#preliminary">Preliminary candidates</a><a href="#electricity">Electricity scale</a><a href="#limits">Limits</a></aside></div>
    </article>
  </main>
}
