'use client'

import { useState } from 'react'
import Link from 'next/link'
import MapView from '@/components/MapView'
import type { Facility } from '@/lib/facilities'
import { calculateImpact, impactTone } from '@/lib/impact'
import { parsePowerKw, powerSummary } from '@/lib/power'

const evidenceLabels: Record<string, string> = { High: 'Strong', Medium: 'Developing', Low: 'Limited', Preliminary: 'Early / unverified' }
const scoreComponents = [['Proximity and scale', '20%', 'Distance, facility class, and known site scale'], ['Electricity and grid', '20%', 'Reported load, substations, and interconnection evidence'], ['Generation and air', '15%', 'Generation type, permits, and documented capacity'], ['Water and cooling', '15%', 'Cooling method and reported water information'], ['Noise and vibration', '15%', 'Cooling, generators, transformers, and complaints'], ['Construction and traffic', '5%', 'Construction activity, duration, and traffic evidence'], ['Land use sensitivity', '5%', 'Homes, schools, flood context, and zoning'], ['Uncertainty buffer', '5%', 'Forward-looking adjustment for missing or changing facts']]

export default function FacilityDetail({ facility }: { facility: Facility }) {
  const [showWhy, setShowWhy] = useState(false)
  const [notice, setNotice] = useState<'shared' | null>(null)
  const [selected, setSelected] = useState(facility)
  const immediateImpact = calculateImpact(facility, 0.25)
  const powerMetric = facility.metrics?.find((metric) => /power|load|capacity/i.test(`${metric.label} ${metric.value}`))
  const powerKw = powerMetric ? parsePowerKw(powerMetric.value) : null
  const power = powerKw ? powerSummary(powerKw) : null
  const evidenceLabel = evidenceLabels[facility.confidence] ?? facility.confidence
  const impactClass = impactTone(immediateImpact.lower, immediateImpact.upper)

  function share() { if (navigator.share) navigator.share({ title: facility.name, url: window.location.href }).catch(() => undefined); else navigator.clipboard?.writeText(window.location.href).then(() => setNotice('shared')) }

  return <main className="detail-page"><header className="topbar"><Link href="/" className="brand"><span className="brand-mark">D</span><span>DATA CENTER <i>IMPACT</i></span></Link><div className="detail-actions"><button className="text-button" onClick={share}>Copy/share page ↗</button><Link href="/" className="back">← Back to map</Link></div></header><div className="detail-wrap">
    <p className="eyebrow">FACILITY PROFILE · {facility.county.toUpperCase()} COUNTY</p><div className="detail-title-row"><div><h1>{facility.name}</h1><div className="detail-meta"><span className={`status-pill ${facility.color}`}>{facility.status === 'operational' ? 'Built' : facility.statusLabel}</span><span>{facility.classLabel}</span><span>Evidence: {evidenceLabel}</span><span>Last reviewed {facility.verified}</span></div>{facility.officialWebsite && <a className="official-link" href={facility.officialWebsite.url} target="_blank" rel="noreferrer">{facility.officialWebsite.label} ↗</a>}</div><a className="outline-button correction-link" href={`https://github.com/christophermowrey/datacenterimpact/issues/new?template=correction.yml&title=${encodeURIComponent(`Correction: ${facility.name}`)}&labels=correction`} target="_blank" rel="noreferrer">Report a correction ↗</a></div>
    {notice === 'shared' && <div className="detail-notice" role="status">Page URL copied to your clipboard.</div>}
    <div className="detail-grid"><section><MapView facilities={[facility]} selected={selected} onSelect={(next) => setSelected(next)} searchedLocation={null} /><h2>What we know</h2><p className="detail-intro">{facility.summary}</p><div className="facts">{facility.metrics?.map((metric) => <div key={metric.label}><small>{metric.label.toUpperCase()}</small><strong>{metric.value}</strong>{metric.note && <span>{metric.note}</span>}</div>)}{power && <div className={power.significant ? 'power-fact significant' : 'power-fact'}><small>ELECTRICITY SCALE</small><strong>{power.label}</strong><span>Based on listed power capacity, not disclosed actual consumption. Significant threshold: 100 homes.</span></div>}<div><small>OPERATOR / DEVELOPER</small><strong>{facility.operator}</strong></div><div><small>LOCATION</small><strong>{facility.locationPrecision === 'exact' ? 'Verified address' : 'Approximate location'} {facility.locationPrecision !== 'exact' && <span className="tooltip-wrap"><button className="tooltip-button" aria-label="Why is this location approximate?">i</button><span className="tooltip-popup" role="tooltip">The reviewed official source does not publish a precise street address. The map point represents the general campus area.</span></span>}</strong></div><div><small>ADDRESS / AREA</small><strong>{facility.address ?? `${facility.city}, ${facility.county} County`}</strong></div></div></section><aside className={`score-panel community-impact-panel ${impactClass}`}><p className="eyebrow">COMMUNITY IMPACT</p><div className="big-score">{immediateImpact.lower}–{immediateImpact.upper}<small> / 100</small></div><strong>{immediateImpact.label} potential impact at approximately 1/4 mile</strong><div className="evidence-summary">Evidence quality: <b>{evidenceLabel}</b></div><p>This is a distance-sensitive screening range, not a prediction of property value, health outcomes, legal risk, or environmental harm. A searched address recalculates the range from its actual distance.</p><button className="outline-button full" onClick={() => setShowWhy((value) => !value)}>How this score works <span>{showWhy ? '↑' : '↓'}</span></button>{showWhy && <div className="why-panel"><p>The lower end reflects supported inputs. The upper end includes conservative proxies for important missing facts.</p>{scoreComponents.map(([name, weight, reason]) => <div className="component-row" key={name}><span><b>{name}</b><small>{reason}</small></span><b>{weight}</b></div>)}<p>A minimal electricity baseline remains because facility demand enters interconnected utility and market systems.</p></div>}</aside></div>
    <section className="detail-section"><div className="section-heading"><div><p className="eyebrow">EVIDENCE TRAIL</p><h2>Sources and timeline</h2></div><span>{facility.sources.length} source{facility.sources.length === 1 ? '' : 's'}</span></div>{facility.milestones?.length ? <div className="timeline">{facility.milestones.map((milestone) => <div key={`${milestone.date}-${milestone.title}`}><span>{milestone.date}</span><p><b>{milestone.title}</b><br />{milestone.description}</p></div>)}</div> : <p className="empty-evidence">No verified milestones are published for this candidate record.</p>}{facility.sources.length ? <div className="source-list">{facility.sources.map((source) => <a className="source-card" href={source.url} target="_blank" rel="noreferrer" key={source.url}><span>{source.archived ? 'ARCHIVED SOURCE CAPTURE' : 'SOURCE RECORD'}</span><strong>{source.title}</strong><small>{source.publisher} · Accessed {source.accessed}</small><p>{source.supports}</p><b>Open source ↗</b></a>)}</div> : <div className="source-card source-empty"><span>RESEARCH STATUS</span><strong>Source review pending</strong><p>This record is retained in the research workflow and is not currently published as verified evidence.</p></div>}</section>
    {facility.unknowns?.length ? <section className="detail-section unknown-section"><p className="eyebrow">KNOWN LIMITATIONS</p><h2>What remains unknown</h2><ul>{facility.unknowns.map((unknown) => <li key={unknown}>{unknown}</li>)}</ul></section> : null}
  </div></main>
}
