export type FacilityStatus = 'operational' | 'construction' | 'announced'
export type Facility = { slug: string; name: string; status: FacilityStatus; statusLabel: string; color: string; class: string; classLabel: string; city: string; county: string; distance: string; score: [number, number]; confidence: string; mapX: number; mapY: number; summary: string; operator: string; verified: string }
export const facilities: Facility[] = [
  { slug: 'databank-houston-hou1', name: 'DataBank HOU1', status: 'operational', statusLabel: 'Operational', color: 'green', class: 'colocation', classLabel: 'Commercial / colocation', city: 'Houston', county: 'Harris', distance: '2.4', score: [32, 48], confidence: 'High', summary: 'A purpose-built colocation facility serving enterprise workloads in northwest Houston.', operator: 'DataBank', verified: '12 Jun 2025', mapX: 67, mapY: 47 },
  { slug: 'skybox-houston', name: 'Skybox Houston', status: 'operational', statusLabel: 'Operational', color: 'green', class: 'colocation', classLabel: 'Commercial / colocation', city: 'Houston', county: 'Harris', distance: '4.1', score: [28, 42], confidence: 'Medium', summary: 'An operational Houston-area data center with published colocation services.', operator: 'Skybox Datacenters', verified: '08 May 2025', mapX: 73, mapY: 39 },
  { slug: 'project-lone-star', name: 'Project Lone Star', status: 'construction', statusLabel: 'Under construction', color: 'amber', class: 'hyperscale', classLabel: 'Major / hyperscale campus', city: 'Katy', county: 'Fort Bend', distance: '7.8', score: [51, 71], confidence: 'Medium', summary: 'A large announced campus with construction activity documented in public records.', operator: 'Undisclosed developer', verified: '23 Apr 2025', mapX: 36, mapY: 45 },
  { slug: 'red-oak-campus', name: 'Red Oak Compute Campus', status: 'announced', statusLabel: 'Announced / planned', color: 'purple', class: 'hyperscale', classLabel: 'Major / hyperscale campus', city: 'Richmond', county: 'Fort Bend', distance: '12.6', score: [44, 68], confidence: 'Preliminary', summary: 'A proposed multi-phase compute campus. Exact parcel and capacity remain under review.', operator: 'Red Oak Infrastructure', verified: '31 Mar 2025', mapX: 43, mapY: 72 },
  { slug: 'energy-way-edge', name: 'Energy Way Edge Site', status: 'announced', statusLabel: 'Announced / planned', color: 'purple', class: 'additional', classLabel: 'Additional compute', city: 'Houston', county: 'Harris', distance: '15.2', score: [24, 39], confidence: 'Low', summary: 'A candidate edge-compute location retained for the optional research layer.', operator: 'Not yet confirmed', verified: '14 Feb 2025', mapX: 81, mapY: 27 },
]
