export type FacilityStatus = 'operational' | 'construction' | 'announced'
export type PublicationStatus = 'published' | 'candidate' | 'demo' | 'archived' | 'excluded'
export type Facility = { slug: string; name: string; publicationStatus: PublicationStatus; status: FacilityStatus; statusLabel: string; color: string; class: string; classLabel: string; city: string; county: string; address?: string; distance?: string; distanceMiles?: number; distanceLabel?: string; score: [number, number]; confidence: string; latitude: number; longitude: number; summary: string; operator: string; verified: string }
export const facilities: Facility[] = [
  { slug: 'databank-houston-hou1', name: 'DataBank HOU1', publicationStatus: 'demo', status: 'operational', statusLabel: 'Operational', color: 'green', class: 'colocation', classLabel: 'Commercial / colocation', city: 'Houston', county: 'Harris', address: '9220 Kirby Dr, Houston, TX 77054', distance: '2.4', score: [32, 48], confidence: 'High', summary: 'A purpose-built colocation facility serving enterprise workloads in northwest Houston.', operator: 'DataBank', verified: '12 Jun 2025', latitude: 29.671, longitude: -95.412 },
  { slug: 'skybox-houston', name: 'Skybox Houston', publicationStatus: 'demo', status: 'operational', statusLabel: 'Operational', color: 'green', class: 'colocation', classLabel: 'Commercial / colocation', city: 'Houston', county: 'Harris', distance: '4.1', score: [28, 42], confidence: 'Medium', summary: 'An operational Houston-area data center with published colocation services.', operator: 'Skybox Datacenters', verified: '08 May 2025', latitude: 29.910, longitude: -95.520 },
  { slug: 'project-lone-star', name: 'Project Lone Star', publicationStatus: 'demo', status: 'construction', statusLabel: 'Under construction', color: 'amber', class: 'hyperscale', classLabel: 'Major / hyperscale campus', city: 'Katy', county: 'Fort Bend', distance: '7.8', score: [51, 71], confidence: 'Medium', summary: 'A large announced campus with construction activity documented in public records.', operator: 'Undisclosed developer', verified: '23 Apr 2025', latitude: 29.780, longitude: -95.820 },
  { slug: 'red-oak-campus', name: 'Red Oak Compute Campus', publicationStatus: 'demo', status: 'announced', statusLabel: 'Announced / planned', color: 'purple', class: 'hyperscale', classLabel: 'Major / hyperscale campus', city: 'Richmond', county: 'Fort Bend', distance: '12.6', score: [44, 68], confidence: 'Preliminary', summary: 'A proposed multi-phase compute campus. Exact parcel and capacity remain under review.', operator: 'Red Oak Infrastructure', verified: '31 Mar 2025', latitude: 29.580, longitude: -95.730 },
  { slug: 'energy-way-edge', name: 'Energy Way Edge Site', publicationStatus: 'demo', status: 'announced', statusLabel: 'Announced / planned', color: 'purple', class: 'additional', classLabel: 'Additional compute', city: 'Houston', county: 'Harris', distance: '15.2', score: [24, 39], confidence: 'Low', summary: 'A candidate edge-compute location retained for the optional research layer.', operator: 'Not yet confirmed', verified: '14 Feb 2025', latitude: 29.930, longitude: -95.340 },
]
