import Link from 'next/link'
import { notFound } from 'next/navigation'
import { facilities } from '@/lib/facilities'
import { scoreLabel } from '@/lib/scoring'

export default async function FacilityPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const facility = facilities.find((item) => item.slug === slug)
  if (!facility) notFound()
  return <main className="detail-page"><header className="topbar"><Link href="/" className="brand"><span className="brand-mark">G</span><span>GRIDLINE <i>HOUSTON</i></span></Link><Link href="/" className="back">← Back to map</Link></header><div className="detail-wrap"><p className="eyebrow">FACILITY PROFILE · {facility.county.toUpperCase()} COUNTY</p><h1>{facility.name}</h1><div className="detail-meta"><span className={`status-pill ${facility.color}`}>{facility.statusLabel}</span><span>{facility.classLabel}</span><span>Last verified {facility.verified}</span></div><div className="detail-grid"><section><div className="detail-map"><span className={`large-pin ${facility.color}`}>●</span><span className="map-label detail-city">{facility.city.toUpperCase()}</span></div><h2>What we know</h2><p className="detail-intro">{facility.summary}</p><div className="facts"><div><small>OPERATOR / DEVELOPER</small><strong>{facility.operator}</strong></div><div><small>ADDRESS / AREA</small><strong>{facility.address ?? `${facility.city}, ${facility.county} County`}</strong></div><div><small>LOCATION PRECISION</small><strong>Approximate area</strong></div></div></section><aside className="score-panel"><p className="eyebrow">NEIGHBORHOOD IMPACT</p><div className="big-score">{facility.score[0]}–{facility.score[1]}</div><strong>{scoreLabel(facility.score)} potential impact</strong><p>Score range for a searched address near this facility. This is not a prediction of property value or health outcomes.</p><div className="confidence-row"><span>Evidence confidence</span><b>{facility.confidence}</b></div><button className="outline-button full">Why this range? <span>↓</span></button></aside></div><section className="evidence"><div><p className="eyebrow">EVIDENCE TRAIL</p><h2>Sources and timeline</h2></div><div className="timeline"><div><span>12 Jun 2025</span><p><b>Record verified</b><br />Current status and location reviewed for publication.</p></div><div><span>09 Jan 2025</span><p><b>Project record created</b><br />Initial source review completed.</p></div></div><div className="source"><span>PRIMARY SOURCE</span><strong>Facility information and public records</strong><button>Open source ↗</button></div></section><p className="disclaimer">Gridline Houston is informational and may contain incomplete or changing information. Always conduct independent legal, environmental, appraisal, and inspection due diligence.</p></div></main>
}
